### ISSUE TITLE
Notice in ResponseFormatter.php line 352 (Undefined index: metadata)

### ISSUE THREAD

**Issue by yuriyant** [graphaware/neo4j-php-client#12] opened 2016-03-04 15:50 UTC
Notice: Undefined index: metadata in Formatter/ResponseFormatter.php on line 352

Query: 

> MATCH (object:Object { id: 1 }), (request:Request { id:2 }), 
>             p = allShortestPaths((request)-[*..10]->(object)) 
> WITH   p 
> LIMIT  20

If the limit is 1-2, then it works, but if you set a limit equal to 20, then error.
When a large limit, array $rel is an array and has the following structure:

`array ( 'directions' => array ( 0 => '->', 1 => '->', 2 => '->', ), 'start' => 'http://neo4j.dvaslona.com/db/data/node/19381', 'nodes' => array ( 0 => 'http://neo4j.dvaslona.com/db/data/node/19381', 1 => 'http://neo4j.dvaslona.com/db/data/node/18692', 2 => 'http://neo4j.dvaslona.com/db/data/node/18693', 3 => 'http://neo4j.dvaslona.com/db/data/node/19380', ), 'length' => 3, 'relationships' => array ( 0 => 'http://neo4j.dvaslona.com/db/data/relationship/401305', 1 => 'http://neo4j.dvaslona.com/db/data/relationship/373216', 2 => 'http://neo4j.dvaslona.com/db/data/relationship/401241', ), 'end' => 'http://neo4j.dvaslona.com/db/data/node/19380', )`

http://dl1.joxi.net/drive/0014/0269/954637/160304/8323e74533.png

**Comment by ikwattro** [comment] 2016-03-04 17:08
Hi @yuriyant ,

Thanks for the report. I'll definitely fix this.

How far are you using the client ? The alpha 4.0 branch is due to be merged soon, it would be advisable to upgrade already as these kind of errors in the formatter would not appear anymore.

Please let me know

**Comment by yuriyant** [comment] 2016-03-04 18:23
Hello @ikwattro ! Thanks for the answer!
In the current version of the client, I have already done the whole project :)
I tested the client version 4.0. Error is no more, but the data for this request were not as expected. As you can see in the screenshot instead of data objects from neo4j, we have an array with a reference to the API.
http://joxi.ru/Dr8d6v3skyKRZr.png

**Comment by ikwattro** [comment] 2016-03-04 18:27
This is really weird, what version of neo4j are you using ?

Nb: I'll fix anyway in 3.x, but I have never encountered the screenshot tbh, so nice to know if this is a bug, thanks for sharing.

**Comment by yuriyant** [comment] 2016-03-04 18:46
I'm using Neo4j 2.3.0

**Comment by ikwattro** [comment] 2016-03-04 19:02
Thanks, I'll definitely look at it this evening, I'll keep posted here with status

**Comment by yuriyant** [comment] 2016-03-04 19:10
Thank you ! I can give you a username, password, and database query. What would make it easier to test.

**Comment by ikwattro** [comment] 2016-03-04 19:12
actually, this would be useful : 

* the code for instantiating the client
* the code used for sending the query and receiving the result

**Comment by ikwattro** [comment] 2016-03-04 19:22
@yuriyant actually it's ok, I could reproduce and am fixing it, will release a new tag in the next hours.

**Comment by yuriyant** [comment] 2016-03-04 19:34
I sent you on the email program code and configuration to connect to the database.

**Comment by ikwattro** [comment] 2016-03-04 19:38
@yuriyant :

Right, I released 3.3.16. Actually returning paths was broken.

Now it will return you a `Path` object containing a sequence of relationships and the length of the path.

ping @frednotet

**Comment by ikwattro** [comment] 2016-03-04 19:39
@yuriyant @frednotet

Please test and report if it fits your use case.

**Comment by ikwattro** [comment] 2016-03-04 19:40
NB: I'm checking now if returning a collection of paths is not broken also, I might release 3.3.17 if it is the case.

**Comment by ikwattro** [comment] 2016-03-04 20:06
Collection of paths fixed in 3.3.17

**Closed by ikwattro** 2016-03-04 20:06 UTC

**Comment by yuriyant** [comment] 2016-03-04 20:08
It's a great job! Thank you very much for a quick help!

**Comment by ikwattro** [comment] 2016-03-04 20:13
With pleasure, on a side note I recommend anyway to upgrade to 4.0, it has support for upcoming Bolt binary protocol in upcoming neo4j 3.0 (some methods from 3.x still need to be ported) but the Result and Records are much more cleaner (not for Path yet :) )

**Comment by ikwattro** [comment] 2016-03-04 20:22
The last commit introduced a bug, fixed in 3.3.18
